### PR TITLE
improved gitignore file

### PR DESCRIPTION
**Pull request by aqreed**
added several file formats to be ignored

### CODE REVIEW

**Comment by Juanlu001** [comment]
Suggestion: just copy-paste from https://www.gitignore.io/

**Comment by aqreed** [comment]
one gitignore to rule them all, @Juanlu001?

**Comment by Juanlu001** [comment]
> one gitignore to rule them all, @Juanlu001?

Or just the Python one :) https://www.gitignore.io/api/python

**Comment by aqreed** [comment]
done!

**Comment by jorgepiloto** [comment]
So sorry for this late merging! Bad practice as maintainer... Merging this and taking a deep look on all the other pull requests :rocket:

**Pull request merged**
